# Site settings
title: "Sur le divan..."
email: francois@cerbelle.net
description: >-
  Le blog qui raconte tout ! Des articles de blog, des vidéos et des 
  pages de tutoriels sur Debian GNU/Linux, les drones, la photo, la 
  vidéo, l'audio, l'électronique, 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: "fr"
show_excerpts: true
date_format: "%d/%m/%Y"
twitter_username: fcerbelle
github_username:  fcerbell
facebook_username: FrancoisCerbelle
instagram_username: francoiscerbelle
linkedin_username: fcerbell
youtube: FrancoisCerbelle
google_analytics: UA-67233700-1
rss: RSS/Atom
author: François Cerbelle
disqus:
    shortname: "surledivan"

# Social share links
pinterest_sharing: true
#instagram_sharing: true
twitter_sharing: true
facebook_sharing: true
#youtube_sharing: true
#vimeo_sharing: true
#soundcloud_sharing: true
#github_sharing: true
tumblr_sharing: true
linkedin_sharing: true
googleplus_sharing: true
reddit_sharing: true
#digg_sharing: true
#stumbleupon_sharing: true
#weibo_sharing: true
#dounban_sharing: true
#hackernews_sharing: true
vk_sharing: true
viadeo_sharing: true


# Build settings
#permalink: pretty
permalink: /:title/
#permalink: :year/:month/:day/:title.html
encoding: utf-8
defaults:
  -
    scope:
      path: ""
    values:
      lang: "fr"
      author: "François Cerbelle"
  -
    scope:
      path: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "pages/en"
    values:
      lang: "en"
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
  -
    scope:
      path: "_drafts/en"
    values:
      lang: "en"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
relative_permalinks: false
sass:
    style: compressed
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
feed:
    posts_limit: 20
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git
  - .gitignore
  - sass
  - .sass-cache
  - package.json
  - gruntfile.js
  - node_modules
  - README.md
  - documentation


