# Site settings
host: 0.0.0.0
title: "Sur le divan... / On the couch"
description: "Le blog qui raconte tout !"
email: francois@cerbelle.net
baseurl: #place folder name if site is served in subfolder
url: #http://www.cerbelle.net/

# Social networks accounts
#pinterest_username: "#"
#instagram_username: "#"
twitter_username: "fcerbelle"
facebook_username: "francois.cerbelle"
youtube_username: "FrancoisCerbelle"
#vimeo_username: "#"
#soundcloud_username: "#"
github_username: "fcerbell"
#tumblr_username: "#"
linkedin_username: "fcerbell"
#googleplus_username: "#"
#reddit_username: "#"
#digg_username: "#"
#stumbleupon_username: "#"
#sinaweibo_username: "#"
#dounban_username: "#"
#hackernews_username: "#"
#vkontakte_username: "#"

# Social sharing

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /:title/
#permalink: :year/:month/:day/:title.html

encoding: utf-8
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "fr"
  -
    scope:
      path: "pages/fr"
    values:
      description: "Site personnel de François Cerbelle"
  -
    scope:
      path: "pages/en"
    values:
      lang: "en"
      description: "François Cerbelle's web site"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
  -
    scope:
      path: "_drafts/en"
    values:
      lang: "en"

disqus:
    shortname: "surledivan"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, documentation]
sass:
    style: compressed


