# Site settings
host: 0.0.0.0
title: "Sur le divan... / On the couch"
description: "Le blog qui raconte tout !"
email: francois@cerbelle.net
baseurl: #place folder name if site is served in subfolder
url: http://fcerbell.github.io/ #http://www.cerbelle.net/

# Social follow links
#pinterest_username: "#"
#instagram_username: "#"
twitter_username: "fcerbelle"
facebook_username: "francois.cerbelle"
youtube_username: "FrancoisCerbelle"
#vimeo_username: "#"
#soundcloud_username: "#"
github_username: "fcerbell"
#tumblr_username: "#"
linkedin_username: "fcerbell"
#googleplus_username: "#"
#reddit_username: "#"
#digg_username: "#"
#stumbleupon_username: "#"
#weibo_username: "#"
#hackernews_username: "#"
#vk_username: "#"

# Social share links
#pinterest_sharing: true
#instagram_sharing: true
twitter_sharing: true
facebook_sharing: true
#youtube_sharing: true
#vimeo_sharing: true
#soundcloud_sharing: true
#github_sharing: true
tumblr_sharing: true
linkedin_sharing: true
googleplus_sharing: true
reddit_sharing: true
#digg_sharing: true
#stumbleupon_sharing: true
weibo_sharing: true
#dounban_sharing: true
#hackernews_sharing: true
vk_sharing: true
viadeo_sharing: true

# Build settings
#permalink: pretty
permalink: /:title/
#permalink: :year/:month/:day/:title.html

encoding: utf-8
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "fr"
  -
    scope:
      path: "pages/fr"
    values:
      description: "Site personnel de François Cerbelle"
  -
    scope:
      path: "pages/en"
    values:
      lang: "en"
      description: "François Cerbelle's web site"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
  -
    scope:
      path: "_drafts/en"
    values:
      lang: "en"

disqus:
    shortname: "surledivan"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, documentation]
sass:
    style: compressed

