# Site settings
host: 0.0.0.0
title: "Sur le divan... / On the couch"
description: "Le blog qui raconte tout !"
email: francois@cerbelle.net
baseurl: #place folder name if site is served in subfolder
url: #http://www.cerbelle.net/
twitter_username: fcerbelle
github_username:  fcerbell
#tumblr: "#"
#pinterest: "#"
#instagram: "#"
facebook: "francois.cerbelle"
youtube: "FrancoisCerbelle"
twitter: "fcerbelle"
github: "fcerbell"

# Build settings
markdown: kramdown
#permalink: pretty
permalink: /:title/
#permalink: :year/:month/:day/:title.html

encoding: utf-8
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "fr"
  -
    scope:
      path: "pages/fr"
    values:
      description: "Site personnel de François Cerbelle"
  -
    scope:
      path: "pages/en"
    values:
      lang: "en"
      description: "François Cerbelle's web site"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
  -
    scope:
      path: "_drafts/en"
    values:
      lang: "en"

disqus:
    shortname: "surledivan"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, documentation]
sass:
    style: compressed


