# Site settings
title: "François Cerbelle"
email: francois@cerbelle.net
description: >-
  Le blog qui raconte tout ! Des articles de blog, des vidéos et des 
  pages de tutoriels sur Debian GNU/Linux, les drones, la photo, la 
  vidéo, l'audio, l'électronique, 
url: "http://fcerbell.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
lang: "fr"
date_format: "%d/%m/%Y"
twitter_username: fcerbelle
github_username:  fcerbell
facebook_username: FrancoisCerbelle
youtube_username: FrancoisCerbelle
instagram_username: francoiscerbelle
linkedin_username: fcerbell
youtube_username: FrancoisCerbelle
meetup_username: "130641882"
skype_username: "fanfan75010"
google_analytics: UA-67233700-1
author: François Cerbelle
disqus:
    shortname: "surledivan"

# Build settings
#incremental: true
permalink: /:title/
encoding: utf-8
defaults:
  -
    scope:
      path: ""
    values:
      lang: "fr"
      author: "François Cerbelle"
  -
    scope:
      path: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "pages/en"
    values:
      lang: "en"
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
  -
    scope:
      path: "_drafts/en"
    values:
      lang: "en"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  math_engine: mathjax

relative_permalinks: false
sass:
    style: compressed
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
feed:
    posts_limit: 20

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git
  - .gitignore
  - sass
  - .sass-cache
  - package.json
  - gruntfile.js
  - node_modules
  - README.md
  - documentation

# Serve settings
host: 0.0.0.0
livereload: true


